# Generated by Django 6.0.7 on 2026-07-13 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='cover_image',
            field=models.URLField(blank=True, help_text='Cover image URL from Edgestore (upload works but persistence TODO)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='editor_font',
            field=models.CharField(blank=True, default='default', help_text='Editor font preference (localStorage only, persistence TODO)', max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='full_width',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='note',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Emoji icon for document (UI renders but persistence TODO)', max_length=64),
        ),
        migrations.AddField(
            model_name='note',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='parent_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_documents', to='notes.note'),
        ),
        migrations.AddField(
            model_name='note',
            name='show_toc',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='note',
            name='small_text',
            field=models.BooleanField(default=False),
        ),
    ]
